# Generated by Django 5.1.3 on 2024-11-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
