# Generated by Django 5.1.3 on 2024-11-06 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_cartitem_restaurant'),
        ('restaurant', '0003_alter_restaurant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
