# Generated by Django 5.1.3 on 2024-11-06 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_cartitem_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='restaurant',
        ),
    ]
