# Generated by Django 5.1.2 on 2024-10-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_customer',
            name='pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='signup_restaurant',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
