# Generated by Django 5.1.2 on 2024-10-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_signup_customer_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_customer',
            name='emailId',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='signup_deliver',
            name='emailId',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='signup_restaurant',
            name='emailId',
            field=models.CharField(max_length=200),
        ),
    ]
