# Generated by Django 5.1.2 on 2024-10-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_signup_customer_emailid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup_Customer',
        ),
        migrations.DeleteModel(
            name='Signup_deliver',
        ),
        migrations.DeleteModel(
            name='Signup_restaurant',
        ),
    ]
